- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    user: "centos"
    machine_type: "{{ lookup('env', 'MACHINE_TYPE') }}"
    credentials_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    zone: "{{ lookup('env', 'ZONE') }}"
    service_account_email:  "{{ lookup('env', 'SERVICE_ACCOUNT_EMAIL') }}"
    ssh_public_key: "{{ lookup('file', lookup('env', 'GCP_SSH_PUBLIC_KEY')) }}"
    instance_name: "{{ lookup('env', 'IMAGE_NAME') }}"
  tasks:
    - include_tasks: read-packer-manifest-gcp.yml

    - name: Provision the test instance
      gce:
         instance_names: "{{ instance_name }}"
         zone: "{{ zone }}"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         state: present
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         disk_size: 40
         metadata: '{"ssh-keys": "{{ user }}: {{ ssh_public_key }}"}'
      register: gce

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 600
        state: started
      with_items: "{{ gce.instance_data }}"

    - name: Make sure the known hosts file exists
      file: "path={{ ssh_known_hosts_file }} state=touch"

    - name: Check host name availability
      shell: "ssh-keygen -f {{ ssh_known_hosts_file }} -F {{ item.public_ip }}"
      with_items: "{{ gce.instance_data }}"
      register: z_ssh_known_host_results
      ignore_errors: yes

    - name: Scan the public key
      shell: "{{ ssh_known_hosts_command}} {{ item.item.public_ip }} >> {{ ssh_known_hosts_file }}"
      with_items: "{{ z_ssh_known_host_results.results }}"
      when: item.stdout == ""

- include: tests/tests.yml
